"""Add lemon_subscription_item_id

Revision ID: aa6ee5845e8b
Revises: a499af19e5c5
Create Date: 2026-02-14 13:24:03.147300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa6ee5845e8b'
down_revision: Union[str, None] = 'a499af19e5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_assets_public_id'), 'assets', ['public_id'], unique=False)
    op.create_index(op.f('ix_assets_restaurant_id'), 'assets', ['restaurant_id'], unique=False)
    op.create_index(op.f('ix_assets_type'), 'assets', ['type'], unique=False)
    op.alter_column('models_3d', 'file_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.alter_column('models_3d', 'thumbnail_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_models_3d_restaurant_id'), 'models_3d', ['restaurant_id'], unique=False)
    op.alter_column('products', 'nutrition',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'ingredients',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'dietary',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'media',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'ui_behavior',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_products_ar_model_id'), 'products', ['ar_model_id'], unique=False)
    op.create_index(op.f('ix_products_order_index'), 'products', ['order_index'], unique=False)
    op.create_index(op.f('ix_products_show_in_menu'), 'products', ['show_in_menu'], unique=False)
    op.alter_column('restaurant_onboardings', 'documents',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('restaurant_onboardings', 'photos',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               type_=postgresql.ARRAY(sa.Text()),
               existing_nullable=True)
    op.alter_column('restaurant_onboardings', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.create_unique_constraint(None, 'restaurant_onboardings', ['restaurant_id'])
    op.drop_constraint(op.f('restaurants_slug_key'), 'restaurants', type_='unique')
    op.add_column('subscriptions', sa.Column('lemon_subscription_item_id', sa.String(length=255), nullable=True))
    op.alter_column('subscriptions', 'next_bill_amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_subscriptions_lemon_subscription_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_lemon_subscription_id'), 'subscriptions', ['lemon_subscription_id'], unique=True)
    op.create_index(op.f('ix_subscriptions_lemon_subscription_item_id'), 'subscriptions', ['lemon_subscription_item_id'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['restaurant_id'])
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(op.f('users_clerk_user_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.alter_column('webhook_events', 'raw_payload',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_webhook_events_lemon_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_lemon_event_id'), 'webhook_events', ['lemon_event_id'], unique=False)
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index(op.f('ix_webhook_events_provider'), 'webhook_events', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_webhook_events_provider'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_lemon_event_id'), table_name='webhook_events')
    op.create_index(op.f('ix_webhook_events_lemon_event_id'), 'webhook_events', ['lemon_event_id'], unique=True)
    op.alter_column('webhook_events', 'raw_payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_clerk_user_id'), table_name='users')
    op.create_index(op.f('ix_users_clerk_user_id'), 'users', ['clerk_user_id'], unique=False)
    op.create_unique_constraint(op.f('users_clerk_user_id_key'), 'users', ['clerk_user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_lemon_subscription_item_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_lemon_subscription_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_lemon_subscription_id'), 'subscriptions', ['lemon_subscription_id'], unique=False)
    op.alter_column('subscriptions', 'next_bill_amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('subscriptions', 'lemon_subscription_item_id')
    op.create_unique_constraint(op.f('restaurants_slug_key'), 'restaurants', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'restaurant_onboardings', type_='unique')
    op.alter_column('restaurant_onboardings', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('restaurant_onboardings', 'photos',
               existing_type=postgresql.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('restaurant_onboardings', 'documents',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_products_show_in_menu'), table_name='products')
    op.drop_index(op.f('ix_products_order_index'), table_name='products')
    op.drop_index(op.f('ix_products_ar_model_id'), table_name='products')
    op.alter_column('products', 'ui_behavior',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'media',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'dietary',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('products', 'ingredients',
               existing_type=postgresql.ARRAY(sa.Text()),
               type_=postgresql.ARRAY(sa.VARCHAR()),
               existing_nullable=True)
    op.alter_column('products', 'nutrition',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_models_3d_restaurant_id'), table_name='models_3d')
    op.alter_column('models_3d', 'thumbnail_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('models_3d', 'file_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_index(op.f('ix_assets_type'), table_name='assets')
    op.drop_index(op.f('ix_assets_restaurant_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_public_id'), table_name='assets')
    op.alter_column('assets', 'url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
