"""add_3d_model_dimensions

Revision ID: c10a454e6181
Revises: aa6ee5845e8b
Create Date: 2026-02-14 23:50:13.885728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c10a454e6181'
down_revision: Union[str, None] = 'aa6ee5845e8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models_3d', sa.Column('height', sa.Float(), nullable=True))
    op.add_column('models_3d', sa.Column('width', sa.Float(), nullable=True))
    op.add_column('models_3d', sa.Column('depth', sa.Float(), nullable=True))
    op.add_column('models_3d', sa.Column('dimension_unit', sa.String(length=10), nullable=False, server_default='cm'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('models_3d', 'dimension_unit')
    op.drop_column('models_3d', 'depth')
    op.drop_column('models_3d', 'width')
    op.drop_column('models_3d', 'height')
    # ### end Alembic commands ###
